Merge dev branch into main
gsmalik030/react-group-project pull request #30
Opened 2023-03-09 13:10 UTC by Victoria129

We have completed the requirements for this project and are now ready to merge into main.

2023-03-09 16:40 UTC, prolajumokeoni requested changes
Hi @gsmalik030 and @Victoria129 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Design follows wireframe design
✔️  Data fetched from SpaceX API endpoints



## Required Changes ♻️

- [ ]  Kindly make sure that the tests written are passing and add more unit tests to your application, please  ensure  you write the new unit tests with React Testing Library and Jest

![Screenshot_751](https://user-images.githubusercontent.com/69638013/224091734-f549daa5-1e6b-4cdc-a0aa-12d9e3da8a26.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- Kindly make sure that for future projects all pull requests created should be reviewed before merging, you currently have some pull requests that were not reviewed before merging, Code reviewing will help you become a better programmer, I suggest you do this for future projects.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-09 16:40 UTC, prolajumokeoni commented on src/component/Navbar.js
> +            <Link to="/Profile">My Profile</Link>
- [ ] Based on the project requirements,  `<NavLink />` should be used for navigation links, NavLink helps  to highlight the active link by providing an attribute called `activeClassName={yourClassName}`

2023-03-10 08:22 UTC, Victoria129 commented on src/component/Navbar.js
> +            <Link to="/Profile">My Profile</Link>
Fixed

2023-03-10 08:27 UTC, DeliceLydia approved these changes
## Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 

## Highlights
- The app is working fine


### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-10 08:31 UTC, merged